#!/bin/sh
set -e

DNS_SERVER="${1:-8.8.8.8}"

NFT_DOMAINS='
openvpn.net .auth0.com .wp.com .oaistatic.com grok.com .oaiusercontent.com
.anthropic.com .mozilla1.com .gravatar.com taiwandaily.net
.sourceforge.net chatgpt.com .fastlydns.net .forbes.com
.fbcdn.net .whatsapp.net .whatsapp.com .linkedin.com .cdn.cloudflare.net
.cedexis-radar.net .gmail.com .kunlungr.com .singular.net
.debian.net .creaders.net .page .ch .xyz .exchange
.tonkeeper.com medium.com .dailyfxasis.com .jitsi.net
.mobilecoin.com .bnbstatic.com .nftpricefloor.com .wenxuecity.com
.openai.com .cloudflareinsights.com .jquery.com discord.com
.airalo.com gitlab.com .xda-developers.com .apkmirror.com .live.com
starlink.com .spacex.com phoronix.com .phoronix.net .sstatic.net
.chrome.com bitinfocharts.com .gvt2.com .gvt1.com .chat .linode.com
.wireguard.com .clubhouse.com .clubhouseapi.com pornhub.com
91porn.com .build .community .guide .biz .gl .dev .google .my .rs .it .ai .goog
.win .edu .mx .ton .blog .us .run .moe .gg .online
.ca .co .de .in .at .tw .gle .fr .org .uk .sg .ru .hk .io
.cc .fb.com .me .ph .coop .be .si .jp .tv .ly
.so .app .udn.com .hk01.com .blocktempo.com .blockchain.com
.brave.com .omtrdc.net .akamaiedge.net .l-msedge.net .dc-msedge.net .licdn.com .linkedin.com .amazonaws.com .okx.com .wordpress.com
.githubassets.com .githubusercontent.com .giphy.com .nvidia.com .yahoo.com .engadget.com
.bbc.com .bloomberg.com dw.com .nytimes.com .aboluowang.com
.zaobao.com .secretchina.com .epochtimes.com .dwnews.com .voachinese.com
.voanews.com .nikkei.com netflix.com .wsj.com imgur.com
.netdna-ssl.com mullvad.net .v2ex.com .tdesktop.com
.cdninstagram.com .instagram.com .ggpht.com .gstatic.com .gstatic.cn
github.com .facebook.com .facebook.net .reddit.com .whoer.net
protonmail.com .duckduckgo.com .twimg.com .twitter.com .viki.com
.bintray.com mvnrepository.com .atlassian.net .googlemail.com
.astrill.com .panoramio.com .googlezip.net .gvt0.com
.gmodules.com .blogger.com .googleblog.com .android.com
.appspot.com .googlesource.com .1e100.net .google.com
.googleapis.com .youtube.com .googlevideo.com ytimg.com
.googleusercontent.com .googledrive.com .yimg.com
'

OUTFILE="nfset.conf"
NFTSET_V4="4#inet#fw4#wgset"
NFTSET_V6="6#inet#fw4#wgset6"

TMPFILE="$(mktemp)"
{
    echo "# Auto-generated by gen-nftset.sh"
    echo "# Timestamp: $(date -R)"
    echo

    count=0
    DOMAIN_PATH=""
    for domain in $NFT_DOMAINS; do
        DOMAIN_PATH="${DOMAIN_PATH}/${domain}"
        count=$((count + 1))

        if [ $count -eq 25 ]; then
            echo "server=${DOMAIN_PATH}/${DNS_SERVER}"
            echo "nftset=${DOMAIN_PATH}/${NFTSET_V4},${NFTSET_V6}"
            echo
            count=0
            DOMAIN_PATH=""
        fi
    done

    # Handle remaining domains if total is not multiple of 20
    if [ $count -ne 0 ]; then
        echo "server=${DOMAIN_PATH}/${DNS_SERVER}"
        echo "nftset=${DOMAIN_PATH}/${NFTSET_V4},${NFTSET_V6}"
        echo
    fi
} > "$TMPFILE"

cp "$TMPFILE" "$OUTFILE"
